### ISSUE TITLE
sdcard.img missing

### ISSUE THREAD

**Issue by synaption** [cdsteinkuehler/br2rauc#13]
I started a fresh project directory from scratch today, and instead of having an sdcard.img it looks like I have an sdcard.img.bmap and an sdcard.img.xz.  I'm not exactly quite sure what to do with these.  I was required to install bmap-tools, and it looks like you are using that to make the upload faster which I am all for.  But it should probably be covered in the readme.

**Comment by synaption** [comment]
To whom it may concern bmaptool copy --bmap sdcard.img.bmap sdcard.img.xz /dev/sda works.

**Comment by cdsteinkuehler** [comment]
Yeah, that should probably be covered in the README, thanks for catching that!

If you don't want to install bmaptools, Etcher will happily work with the *.img.xz file, or you can just "xzcat sdcard.img.bmap | sudo dd of=/dev/sdxyz".

**Comment by cdsteinkuehler** [comment]
Finally got around to updating the README in commit d10df3af80e771624971fd01786cec0d4cd07a12.
