### ISSUE TITLE
rauc bundles don't get a version number

### ISSUE THREAD

**Issue by ghost** [cdsteinkuehler/br2rauc#14]
Here https://github.com/cdsteinkuehler/br2rauc/blame/master/board/raspberrypi/post-image.sh#L66 and in the other manifests a version number is supposed to end up in the rauc manifest for each bundle but the $VERSION variable is never defined. This results in the generated bundle not having a version number and `rauc status` not being aware of any installed versions.

I solved this by setting `VERSION=$(git describe)` at the top of the script but that might not work for every use-case so I don't know exactly how to contribute a fix for this.

**Comment by cdsteinkuehler** [comment]
I am using br2rauc alongside another git project which checks out the br2rauc project and the Buildroot project as git submodules.  I use `git describe --tags --long --always` to get the version of this "container" git repository which I use as `VERSION`.  I need to see if I can craft something that will work by default with a stand-alone br2rauc working copy but can also be used in a more complex environment.  Suggestions welcome, with or without any code.

**Comment by cdsteinkuehler** [comment]
The version handling logic has been updated in commit eb6feb1234b609f1dba1287819697055861ea413.
If VERSION is not set (eg: exported by a top-level Makefile or similar automated build process) fall back to using the Buildroot version.
