### ISSUE TITLE
Why is kernel version 5.10 used?

### ISSUE THREAD

**Issue by synaption** [cdsteinkuehler/br2rauc#16]
I'm trying to upgrade to 5.15 by changing BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION to the current master branch of the pi kernel repo.  The problem is that updates fail with the error:  ```LastError: Failed mounting bundle: Failed to open /dev/mapper/control: No such file or directory```.  Is there any other reason that kernel 5.10 is chosen over the newer 5.15?

**Comment by cdsteinkuehler** [comment]
I am using kernel 5.15 without issue, however I am using a second BR2_EXTERNAL directory along with the br2rauc project and it looks like I didn't update the br2rauc default projects.  To change the kernel version you just have to update the git hash.  The problem with updates sounds like a kernel configuration issue, make sure you are using the linux.fragment (which enables verity & squashfs) with your kernel config.

**Comment by synaption** [comment]
Thanks.  I ended up copying this line over from the home assistant os config: ```BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION="https://github.com/raspberrypi/linux/archive/1.20220331.tar.gz"```
I dont know why: ```BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION="$(call github,raspberrypi,linux,f4c7d81d74d414ab0d4674c9bd3b132ed5f2df35)/linux-f4c7d81d74d414ab0d4674c9bd3b132ed5f2df35.tar.gz"```
did not work.  It could have been some confusion between full and partial rebuilds.

**Comment by cdsteinkuehler** [comment]
I have pushed an update 53e60c8a65936dca50822146bc76f673bdb0a4fc that enables 5.15 kernels and I have verified the generated update bundles install as expected:
````
$ rauc install /data/rootfs.raucb
installing
  0% Installing
  0% Determining slot states
 20% Determining slot states done.
 20% Checking bundle
 20% Verifying signature
 40% Verifying signature done.[   37.231137] loop0: detected capacity change from 0 to 85843

 40% Checking bundle done.
[   37.273550] loop0: detected capacity change from 85843 to 85840
 40% Checking manifest contents
 60% Checking manifest contents done.
[   37.315573] device-mapper: ioctl: 4.45.0-ioctl (2021-03-22) initialised: dm-devel@redhat.com
[   37.352873] device-mapper: verity: sha256 using implementation "sha256-generic"
 60% Determining target install group
 80% Determining target install group done.
 80% Updating slots
 80% Checking slot rootfs.1
 90% Checking slot rootfs.1 done.
 90% Copying image to rootfs.1
100% Copying image to rootfs.1 done.
100% Updating slots done.
100% Installing done.
Installing `/data/rootfs.raucb` succeeded
$ 
````
