### ISSUE TITLE
SCP is failing | authorization failure

### ISSUE THREAD

**Issue by Sourabh-ALTEN** [cdsteinkuehler/br2rauc#19]
Hello,

I have to transfer some files to raspberry pi and I am using scp for this. But it's asking for password and I am not sure which password to use. I have set `PubkeyAuthentication no` in `sshd_config`. But still it's the same. Could you please let me know if there is any default password generated during ssh key creation?

**Comment by cdsteinkuehler** [comment]
Your question does not make any sense.  The default br2rauc configuration allows for console login with no password and no network login.  There is no ssh server and no scp client installed, so if you have these present you have customized the configuration and any key generation or passwords would be setup how you configured them (or with the Buildroot defaults).
