### ISSUE TITLE
[Question] Unexpected Behavior in Boot Slot Switching: BOOT_ORDER Remains Unchanged

### ISSUE THREAD

**Issue by Jierger** [cdsteinkuehler/br2rauc#26]
Hi Charles ,

I've noticed that if it's not marked, the system eventually switches boot slots, but the BOOT_ORDER doesn't change accordingly. It is expected to change from (A B) to (B A), but it remains (A B) to (A B). Is this the expected behavior? At this point, the marked order still doesn't change. Although I am not running this on a Raspberry Pi, I would like to confirm if you are experiencing the same behavior.

![image](https://github.com/cdsteinkuehler/br2rauc/assets/8401549/f5f82372-70d9-4638-b508-53b78a833620)

**Comment by cdsteinkuehler** [comment]
BOOT_ORDER essentially indicates which partition has the "newest" or most recently installed update, and is modified when you use RAUC to install an update bundle.   My U-Boot scripts were based on, and attempt to match the functionality of, the contributed U-Boot integration script provided with RAUC: https://github.com/rauc/rauc/blob/master/contrib/uboot.sh

**Comment by Jierger** [comment]
Thank you very much for your response. I will follow your advice and check further. I will also post my question on to the RAUC repo.
