### ISSUE TITLE
defconfig file for MyCoolProject example

### ISSUE THREAD

**Issue by synaption** [cdsteinkuehler/br2rauc#3]
I'm not sure if this is a typo or not, but the MyCoolProject example does have "raspberrypicm4io_64_rauc_defconfig" at the end of the make line.  I am also wondering if there is a way to specify multiple defconfig files for the same build.  Specifically I am trying to have two BR2_ROOTFS_OVERLAY paths specified with one being in my other buildroot-external.  I'm not sure of the best way to do that without changing raspberrypicm4io_64_rauc_defconfig.

**Comment by cdsteinkuehler** [comment]
The "MyCoolProject" is just somewhat of a hint and the trailing three dots are intended to indicate the rest of the command (such as your desired defconfig file).  I'll think about how I can make that somewhat clearer, suggestions welcome.

As for maintaining a defconfig, there isn't really an easy way to do that with Buildroot.  There were some attempts over the years to support config fragments for the defconfig files the way you can use them for Busybox, U-Boot, and Linux, but that never got integrated.  You can maintain a fragment file on your own and use the Buildroot tools to generate your defconfig file prior to running Buildroot's make, but that's somewhat complicated.  I simply add a new defconfig for my project in the second Buildroot external directory and use that when starting from scratch.  To keep my custom defconfig and the br2rauc defconfig aligned with each other and with the Buildroot supplied RPi CM4 defconfig I just use diff and manually merge changes forwards/backwards as needed.  That's worked reasonably well for me so far.

**Comment by cdsteinkuehler** [comment]
I hopefully clarified this process in commit d10df3af80e771624971fd01786cec0d4cd07a12.
