### ISSUE TITLE
Use `/chosen/kaslr-seed` and `/chosen/rng-seed` from fw-dtb.

### ISSUE THREAD

**Issue by ghost** [cdsteinkuehler/br2rauc#7]
Some background here: https://github.com/raspberrypi/firmware/issues/1595

Can we just copy those two properties from the fw-dtb into the one we load from the rootfs before booting the kernel? The first one is necessary for kernel address layout randomization, the second one for initializing the kernel random seed during very early boot.

**Comment by cdsteinkuehler** [comment]
I believe just copying the values should be fine.  I'm still working my way up the learning curve with U-Boot and device tree manipulations, so PR (or any hints on how best to implement this) appreciated!

**Comment by cdsteinkuehler** [comment]
I have attempted to copy the chosen values from the FW loaded dtb to the dtb loaded by U-Boot and I do not think this is possible given the limitations of the U-Boot fdt shell command.  If you need these values for now you will have to use the firmware loaded device-tree.  I am open to a U-Boot patch that will support copying these settings, but don't currently have the time or expertise to try and implement this.

**Comment by ghost** [comment]
> but don't currently have the time or expertise to try and implement this.

That is, tbh. how I feel as well right now. I'll try getting back to this eventually but can't really spend any time on this right now.

Thanks for taking a look in any case! :)

**Comment by cdsteinkuehler** [comment]
I've asked about this a bit on the U-Boot IRC and I may try implementing this as part of the ft_board_setup() function which is called just prior to actually booting the kernel.

NOTE: I see the kaslr-seed entry populated by the firmware, but I'm *NOT* seeing an entry for rng-seed.  This is booting Buildroot and using the firmware loaded device-tree.  I'll have to double-check the stock RPi OS, maybe I've got something messed up with the RNG in my Buildroot generated device-tree.

UPDATE: I see the /chosen/rng-seed node in the fw loaded fdt when examining it with U-Boot, but it's not listed in /proc/device-tree/chosen/ once Linux is up and running.

**Comment by ghost** [comment]
> UPDATE: I see the /chosen/rng-seed node in the fw loaded fdt when examining it with U-Boot, but it's not listed in /proc/device-tree/chosen/ once Linux is up and running.

Huh, good find. I suppose that's a kernel security feature, maybe? I wonder why this isn't done for the kaslr seed as well then though.

**Comment by cdsteinkuehler** [comment]
Test with this Pull Request and see if it works for you: https://github.com/cdsteinkuehler/br2rauc/pull/9

The code looks OK and I only had a couple issues with the text of the comments but I haven't tested it yet.

**Comment by cdsteinkuehler** [comment]
The initial version copied all parameters under a node, which means /chosen/bootargs was getting copied which would break the RAUC U-Boot script logic used to determine which partition to use for the rootfs.  Now updated to only copy specific parameters.

NOTE: I have verified via boot logs the Linux kernel appears to be seeing and using the /chosen/rng-seed entry.  The /chosen/kaslr-seed requires CONFIG_RANDOMIZE_BASE which is disabled in the default RPi Linux kernel configurations: https://github.com/devicetree-org/dt-schema/blob/19d754e9e2b6b319bbfd98efa26c1578e61a088a/schemas/chosen.yaml#L35-L53

Resolved by commit 5551e9f0126dc21e632ff3a7c5f2b427c2b04106.

**Comment by ghost** [comment]
Thanks for working on this. I opened https://github.com/raspberrypi/linux/issues/4989 to ask why KASLR isn't enabled by default on the pi4. (it was added to the pi in 2017 as far as I could tell.)

Edit: it has now been added back to the pi4 defconfig.
