### ISSUE TITLE
Rpi-firmware on RPI4B cannot find  devicetree on boot

### ISSUE THREAD

**Issue by leonardoaraujodf** [cdsteinkuehler/br2rauc#8]
When the RPI4B board is booting, the rpi-firmware knows based on the hardware version which devicetree to load.
The firmware looks for a devicetree named `bcm2711-rpi-4-b.dts` , but once the vfat partition only contains the CM4 devicetree `bcm2711-rpi-cm4.dts`, the rpi-firmware cannot find the devicetree and it hangs.

So let's add support for the RPI4B so that we can use the br2rauc in it :)

**Comment by cdsteinkuehler** [comment]
Agreed!

I am working on adding support for more than just the CM4 based on how Buildroot handles the RPi boards.  I am currently just targeting 64-bit builds for the CM4 and RPi 4B, but it should be fairly straight-forward to support other RPi boards in the same manner.

**Comment by cdsteinkuehler** [comment]
RPi 4B support added with commit: f8b8dff09ac7afaaaf3c1fc8236209378df3fb51
